name: CI/CD Build → Push → Deploy (Helm)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nginx-helm-demo:latest

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy with Helm
        run: |
          helm upgrade --install nginx-helm ./helm-chart \
            --namespace default \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/nginx-helm-demo \
            --set image.tag=latest \
            --create-namespace

