name: Deploy with Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1️⃣ Setup kubeconfig before Helm/Kubectl
      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      # 2️⃣ Now Helm can connect to the cluster
      - name: Deploy with Helm
        run: |
          helm upgrade --install nginx-helm ./helm-chart

